accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products import views as productview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', productview.homepage, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create', views.create, name='create'),
    path('<int:product_id>/', views.detail, name='product_detail'),
    path('<int:product_id>/upvote/', views.upvote, name='upvote'),
    path('<int:product_id>/edit/', views.edit, name='edit'),
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Product(models.Model):
    title = models.CharField(max_length=255)
    url = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    votes_total = models.IntegerField(default=1)
    image = models.ImageField(upload_to='images/products/')
    icon = models.ImageField(upload_to='images/products/icons/')
    body = models.TextField()
    hunter = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %d %Y')

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({'class': 'form-control'})
        self.fields['hunter'].widget.choices = [('', 'Select Hunter'), ] + list(self.fields['hunter'].widget.choices)[1:]
    
    class Meta:
        model = Product
        # fields = '__all__'
        exclude = ['pub_date', 'votes_total']
        widgets = {
            'url': forms.TextInput()
        }
        error_messages = {
            'title': {
                'required': 'Title is Required'
            },
            'url': {
                'required': 'Url is Required'
            },
            'image': {
                'required': 'Image is Required'
            },
            'icon': {
                'required': 'Icon is Required'
            },
            'body': {
                'required': 'Body is Required'
            },
            'hunter': {
                'required': 'Please select Hunter'
            },
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth


def signup(request):
    if request.method == 'POST':
        username = request.POST['username'].strip()
        password1 = request.POST['password1'].strip()
        password2 = request.POST['password2'].strip()
        context = {
            'username': username,
        }

        if username == '' or password1 == '' or password2 == '':
            context['error'] = 'Please Fillup username and both passwords.'
            return render(request, 'accounts/signup.html', context)
        elif password1 != password2:
            context['error'] = 'passwords do not match.'
            return render(request, 'accounts/signup.html', context)
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = User.objects.create_user(username=username, password=password1)
            auth.login(request, user)
            return redirect('home')
        else:
            context['error'] = 'username has already been taken.'
            return render(request, 'accounts/signup.html', context)
    else:
        return render(request, 'accounts/signup.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username'].strip()
        password = request.POST['password'].strip()
        next_url = request.POST['next_url'].strip()
        context = {
            'username': username,
            'next_url': next_url,
        }

        if username == '' or password == '':
            context['error'] = 'Please Fillup both username and password.'
            return render(request, 'accounts/login.html', context)

        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect(next_url)
        else:
            context['error'] = 'Invalid username or password.'
            return render(request, 'accounts/login.html', context)
    else:
        return render(request, 'accounts/login.html', {'next_url': request.GET.get('next', 'home')})


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('home')

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import F
from .forms import ProductForm
from .models import Product


def homepage(request):
    products = Product.objects.order_by('-votes_total', 'title')
    return render(request, 'products/home.html', {'products': products})


@login_required()
def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = ProductForm()
            return render(request, 'products/create.html', {
                'form': form,
                'submit_success': 'Thanks! Your Data handled Successfully'
                }
            )
        else:
            return render(request, 'products/create.html', {'form': form})
    else:
        form = ProductForm()
        return render(request, 'products/create.html', {'form': form})


@login_required()
def edit(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            product = get_object_or_404(Product, pk=product_id)
            form = ProductForm(instance=product)
            return render(request, 'products/edit.html', {
                'form': form,
                'submit_success': 'Thanks! Your Data handled Successfully',
                'product': product
                }
            )
        else:
            return render(request, 'products/edit.html', {'form': form, 'product': product})
    else:
        form = ProductForm(instance=product)
        return render(request, 'products/edit.html', {'form': form, 'product': product})


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'products/detail.html', {'product': product})


@login_required()
def upvote(request, product_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=product_id)
        product.votes_total = F('votes_total') + 1
        product.save()
        return redirect(request.POST.get('redirect_after'))
    elif request.method == 'GET':
        return redirect('product_detail', product_id=product_id)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login!{% endblock %}

{% block content %}
    <div class="container">
        <h1>Login!</h1>

        {% if error or success %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ error }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        {% endif %}

        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ username }}">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
            <input type="hidden" name="next_url" value="{{ next_url }}">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up!{% endblock %}

{% block content %}
    <div class="container">
        <h1>Sign up!</h1>

        {% if error or success %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ error }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        {% endif %}

        <form method="post" action="{% url 'signup' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ username }}">
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" class="form-control" id="password1" name="password1">
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" class="form-control" id="password2" name="password2">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
    </div>
{% endblock %}

products/templates/products/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create Product{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container" style="margin-bottom: 100px;">
        <h1>Create Product</h1>

        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <ul>
                Errors:
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        {% if submit_success %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ submit_success }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        <form method="post" action="{% url 'create' %}" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'select2/dist/js/select2.full.min.js' %}"></script>
<script>
$(document).ready(function(){
    $("#id_hunter").select2();
    $("#s").select2();
});
</script>
{% endblock %}

products/templates/products/detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}
    <div class="container" style="margin-bottom: 100px;">
        <div class="row">
            <div class="col-2">
                <img src="{{ product.icon.url }}" class="img-fluid" alt="{{ product.title }}">
            </div>
            <div class="col-10">
                <a href="{{ product.url }}" target="_blank"><h3>{{ product.title }}</h3></a>
            </div>
        </div>

        <div class="row" style="margin-top:10px;">
            <div class="col-8">
                <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.title }}">
            </div>
            <div class="col-4">
                <a href="javascript:document.getElementById('form_upvote_{{ product.id }}').submit();" class="btn btn-primary btn-lg upvote-btn">
                    <span class="oi oi-arrow-thick-top" style="margin-right: 5px;"></span>Upvote {{ product.votes_total }}
                </a>
                <br />
                {% if request.user.is_authenticated and request.user == product.hunter %}
                <a href="{% url 'edit' product.id %}" class="btn btn-success btn-lg" style="margin-top:10px;">
                    <span class="oi oi-task"></span> Edit
                </a>
                {% endif %}
                <form id="form_upvote_{{ product.id }}" method="post" action="{% url 'upvote' product.id %}">
                {% csrf_token %}
                <input type="hidden" name="redirect_after" value="{{ request.path }}" />
            </form>
            </div>
        </div>

        <div class="row" style="margin-top:10px;">
            <div class="col-4">
                <h4><span class="oi oi-magnifying-glass"></span> Hunted by {{ product.hunter.username }}</h4>
            </div>
            <div class="col-4 text-right">
                <h4><span class="oi oi-clock"></span> {{ product.pub_date_pretty }}</h4>
            </div>
        </div>

        <div class="row" style="margin-top:10px;">
            <div class="col-8 text-justify">
                <p>{{ product.body|linebreaks }}</p>
            </div>
        </div>
    </div>
{% endblock %}

products/templates/products/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Product{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container" style="margin-bottom: 100px;">
        <h1>Edit Product</h1>

        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <ul>
                Errors:
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        {% if submit_success %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ submit_success }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        <form method="post" action="{% url 'edit' product.id %}" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'select2/dist/js/select2.full.min.js' %}"></script>
<script>
$(document).ready(function(){
    $("#id_hunter").select2();
});
</script>
{% endblock %}

products/templates/products/home.html
{% extends 'base.html' %}
{{ request.path }}
{% block content %}
<div class="container">
    {% for product in products %}
    <div class="row">
        <div class="col-2">
            <img src="{{ product.icon.url }}" class="img-fluid" />
        </div>
        <div class="col-6">
            <a href="{% url 'product_detail' product.id %}"><h2>{{ product.title }}</h2></a>
            <p>{{ product.body|truncatechars:200|linebreaks }}</p>
        </div>
        <div class="col-4">
            <a href="javascript:document.getElementById('form_upvote_{{ product.id }}').submit();" class="btn btn-primary btn-lg upvote-btn">
                <span class="oi oi-arrow-thick-top" style="margin-right: 5px;"></span>Upvote {{ product.votes_total }}
            </a>
            <form id="form_upvote_{{ product.id }}" method="post" action="{% url 'upvote' product.id %}">
                {% csrf_token %}
                <input type="hidden" name="redirect_after" value="{{ request.path }}" />
            </form>
        </div>
    </div>
    <hr />
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'open-iconic-master/font/css/open-iconic-bootstrap.min.css' %}">
{% block styles %}{% endblock %}
<title>{% block title %}{% endblock %} :: ProductHunt</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <svg width="40" height="40" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M40 20c0 11.046-8.954 20-20 20S0 31.046 0 20 8.954 0 20 0s20 8.954 20 20" fill="#DA552F"></path><path d="M22.667 20H17v-6h5.667a3 3 0 0 1 0 6m0-10H13v20h4v-6h5.667a7 7 0 1 0 0-14" fill="#FFF"></path></g></svg>
                ProductHunt
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:">Logged In: <strong>{{ user.username }}</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create' %}"><span class="oi oi-plus" title="Create Product"></span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:{$('#logout').submit()}">Logout</a>
                        <form id="logout" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

{% block content %}{% endblock %}

<footer class="text-muted text-center fixed-bottom">
    <div class="container text-center">
        <p>&copy; Rezwanul Haque Shiplu {% now "Y" %}</p>
    </div>
</footer>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% block scripts %}{% endblock %}
</body>
</html>